### ISSUE TITLE
does not work with node 9.3

### ISSUE THREAD

**Issue by logicminds** [blainesch/pry.js#51]
Getting the following error with node 9.3

```
TypeError: process._tickDomainCallback is not a function
    at Function.module.exports.runLoopOnce (/Users/user1/project/node_modules/deasync/index.js:65:11)
    at SyncHighlight.highlight (/Users/user1/project/node_modules/pryjs/build/pry/sync_highlight.js:49:19)
    at SyncHighlight.code_snippet (/Users/user1/project/node_modules/pryjs/build/pry/sync_highlight.js:62:20)
    at File.formatted_content_by_line (/Users/user1/project/node_modules/pryjs/build/pry/file.js:46:61)
    at Whereami.execute (/Users/user1/project/node_modules/pryjs/build/pry/commands/whereami.js:33:34)
    at App.find_command (/Users/user1/project/node_modules/pryjs/build/pry/app.js:65:34)
    at SyncPrompt.<anonymous> (/Users/user1/project/node_modules/pryjs/build/pry/app.js:3:61)

```

**Comment by logicminds** [comment]
This appears to be an issue with deasync

**Comment by logicminds** [comment]
Looks like it was fixed in deasync version :    0.1.12

https://github.com/abbr/deasync/commit/3638d542b6c0fece8d7ddf2a02d9bcd8b1109bcb

Would need to update the deasync version in package.json
